# Generated by Django 5.2 on 2025-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "bankid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("bankname", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("status", models.IntegerField(max_length=1)),
                ("price", models.IntegerField()),
                ("questions", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "questionid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("type", models.IntegerField(max_length=1)),
                ("content", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User_Bank_Status",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=100,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("userid", models.BigIntegerField(default=0, max_length=15)),
                ("bankid", models.BigIntegerField(default=0, max_length=15)),
                ("finished", models.IntegerField(default=0)),
                ("unlocked", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User_Question_Status",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=100,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("userid", models.BigIntegerField(default=0, max_length=15)),
                ("questionid", models.BigIntegerField(default=0, max_length=15)),
                ("finished", models.IntegerField(default=0)),
                ("time", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ZAdmin",
            fields=[
                (
                    "adminid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("adminname", models.CharField(default="CodeZ_Admin", max_length=50)),
                ("password", models.CharField(default="159159159", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ZUser",
            fields=[
                (
                    "userid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=50)),
                ("phonenumber", models.BigIntegerField()),
                ("thirdpartyauth", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ZUserProfile",
            fields=[
                (
                    "userid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("displayname", models.CharField(max_length=50)),
                ("age", models.IntegerField(max_length=3)),
                ("gender", models.CharField(max_length=1)),
                ("zcoins", models.BigIntegerField(default=0)),
                ("avatar", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("school", models.CharField(blank=True, max_length=30)),
                ("corrects", models.IntegerField(default=0)),
                ("finishes", models.IntegerField(default=0)),
                ("medals", models.CharField(blank=True, max_length=255)),
                ("displaymedals", models.CharField(blank=True, max_length=255)),
                ("unlockedbanks", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
