# Generated by Django 5.2 on 2025-04-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "bankid",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("bankname", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("status", models.IntegerField(max_length=1)),
                ("price", models.IntegerField()),
                ("questions", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "questionid",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("type", models.IntegerField(max_length=1)),
                ("content", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ZUser",
            fields=[
                (
                    "userid",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=50)),
                ("phonenumber", models.IntegerField(max_length=15)),
                ("thirdpartyauth", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ZUserProfile",
            fields=[
                (
                    "userid",
                    models.IntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("displayname", models.CharField(max_length=50)),
                ("age", models.IntegerField(max_length=3)),
                ("gender", models.CharField(max_length=1)),
                ("zcoins", models.IntegerField(default=0)),
                ("avatar", models.ImageField(upload_to="avatars")),
                ("description", models.TextField()),
                ("school", models.CharField(max_length=30)),
                ("corrects", models.IntegerField(default=0)),
                ("finishes", models.IntegerField(default=0)),
                ("medals", models.CharField(max_length=255)),
                ("displaymedals", models.CharField(max_length=255)),
                ("unlockedbanks", models.CharField(max_length=255)),
            ],
        ),
    ]
