# Generated by Django 5.2 on 2025-04-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zuser",
            name="phonenumber",
            field=models.IntegerField(),
        ),
    ]
