# Generated by Django 5.2 on 2025-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_bank_status",
            name="id",
            field=models.BigIntegerField(
                default=10,
                max_length=15,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user_question_status",
            name="id",
            field=models.BigIntegerField(
                default=10,
                max_length=15,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
