# Generated by Django 5.2 on 2025-04-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0002_alter_zuser_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="bankid",
            field=models.BigIntegerField(
                max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="questionid",
            field=models.BigIntegerField(
                max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="zuser",
            name="phonenumber",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="zuser",
            name="userid",
            field=models.BigIntegerField(
                max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="userid",
            field=models.BigIntegerField(
                max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="zcoins",
            field=models.BigIntegerField(default=0),
        ),
    ]
