# Generated by Django 5.2 on 2025-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0002_alter_user_bank_status_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_bank_status",
            name="id",
            field=models.BigIntegerField(
                default=0, max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user_question_status",
            name="id",
            field=models.BigIntegerField(
                default=0, max_length=15, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
