# Generated by Django 5.2 on 2025-05-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0003_alter_user_bank_status_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question_Comment_Status",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=0,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("userid", models.BigIntegerField(default=0, max_length=15)),
                ("questionid", models.BigIntegerField(default=0, max_length=15)),
                ("comment", models.TextField()),
            ],
        ),
    ]
