# Generated by Django 5.2 on 2025-04-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0003_alter_bank_bankid_alter_question_questionid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zuser",
            name="thirdpartyauth",
            field=models.CharField(default="", max_length=255),
        ),
    ]
