# Generated by Django 5.2 on 2025-05-07 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0004_question_comment_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Question_Comment_Status",
            new_name="Question_Comment",
        ),
    ]
