# Generated by Django 5.2 on 2025-04-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0004_alter_zuser_thirdpartyauth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zuser",
            name="thirdpartyauth",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
