# Generated by Django 5.2 on 2025-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0005_alter_zuser_thirdpartyauth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZAdmin",
            fields=[
                (
                    "adminid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="avatar",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="displaymedals",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="medals",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="school",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="zuserprofile",
            name="unlockedbanks",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
