# Generated by Django 5.2 on 2025-05-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0005_rename_question_comment_status_question_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="question_comment",
            name="time",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="question_comment",
            name="comment",
            field=models.TextField(default=""),
        ),
    ]
