# Generated by Django 5.2 on 2025-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0006_question_comment_time_alter_question_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_bank_status",
            name="bankid",
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user_bank_status",
            name="userid",
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user_question_status",
            name="questionid",
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user_question_status",
            name="userid",
            field=models.BigIntegerField(max_length=15),
        ),
    ]
