# Generated by Django 5.2 on 2025-04-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0006_zadmin_alter_zuserprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zadmin",
            name="adminname",
            field=models.CharField(default="CodeZ_Admin", max_length=50),
        ),
        migrations.AlterField(
            model_name="zadmin",
            name="password",
            field=models.CharField(default="159159159", max_length=50),
        ),
    ]
