# Generated by Django 5.2 on 2025-05-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0007_alter_user_bank_status_bankid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question_comment",
            name="questionid",
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name="question_comment",
            name="userid",
            field=models.BigIntegerField(max_length=15),
        ),
    ]
