# Generated by Django 5.2 on 2025-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0007_zadmin_adminname_alter_zadmin_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
