# Generated by Django 5.2 on 2025-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codez", "0008_question_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User_Bank_Status",
            fields=[
                (
                    "userid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("bankid", models.BigIntegerField(max_length=15, unique=True)),
                ("finished", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User_Question_Status",
            fields=[
                (
                    "userid",
                    models.BigIntegerField(
                        max_length=15, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("questionid", models.BigIntegerField(max_length=15, unique=True)),
                ("finished", models.IntegerField(default=0)),
                ("time", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
            ],
        ),
    ]
